# Generated by Django 3.0.10 on 2021-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_subject'),
        ('videos', '0006_remove_video_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(default=None, editable=False, unique=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='videos.Course'),
        ),
    ]
