# Generated by Django 3.0.10 on 2021-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
