# Generated by Django 3.0.10 on 2021-04-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_remove_teacher_course'),
        ('videos', '0010_auto_20210403_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=None, editable=False, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default=None, max_length=20, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
