# Generated by Django 3.0.10 on 2021-03-17 17:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('image', models.ImageField(default='media/teachers/default.png', upload_to='media/teachers')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
