# Generated by Django 3.0.10 on 2021-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='superuser'),
        ),
    ]
