# Generated by Django 3.0.10 on 2021-03-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_superuser',
        ),
    ]
