# Generated by Django 3.0.10 on 2021-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacher_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=None, max_length=20, verbose_name='subject'),
        ),
    ]
