# Generated by Django 3.0.10 on 2021-04-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_course_teacher'),
        ('teachers', '0004_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='videos.Course'),
        ),
    ]
