# Generated by Django 3.0.10 on 2021-04-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
    ]
